build: false

environment:
  PYTHON: "C:\Python37-x64"

  CONAN_REFERENCE: "OpenSubdiv/3.4.3"
  CONAN_USERNAME: "latios96"
  CONAN_LOGIN_USERNAME: "latios96"
  CONAN_CHANNEL: "stable"
  CONAN_UPLOAD: "https://api.bintray.com/conan/latios96/my_conan"

  matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017


install:
  - C:\Python37-x64\Scripts\pip.exe install conan --upgrade
  - C:\Python37-x64\Scripts\pip.exe install conan_package_tools
  - C:\Python37-x64\Scripts\conan user # It creates the conan data directory

test_script:
  - C:\Python37-x64\python build.py
